/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as TestsProxyRouteImport } from './routes/tests/proxy'
import { Route as TestsPromiseRouteImport } from './routes/tests/promise'
import { Route as TestsMountingRouteImport } from './routes/tests/mounting'
import { Route as TestsDerivedChainRouteImport } from './routes/tests/derived-chain'
import { Route as TestsCyclicDependencyRouteImport } from './routes/tests/cyclic-dependency'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsProxyRoute = TestsProxyRouteImport.update({
  id: '/tests/proxy',
  path: '/tests/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsPromiseRoute = TestsPromiseRouteImport.update({
  id: '/tests/promise',
  path: '/tests/promise',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsMountingRoute = TestsMountingRouteImport.update({
  id: '/tests/mounting',
  path: '/tests/mounting',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsDerivedChainRoute = TestsDerivedChainRouteImport.update({
  id: '/tests/derived-chain',
  path: '/tests/derived-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsCyclicDependencyRoute = TestsCyclicDependencyRouteImport.update({
  id: '/tests/cyclic-dependency',
  path: '/tests/cyclic-dependency',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/tests/cyclic-dependency': typeof TestsCyclicDependencyRoute
  '/tests/derived-chain': typeof TestsDerivedChainRoute
  '/tests/mounting': typeof TestsMountingRoute
  '/tests/promise': typeof TestsPromiseRoute
  '/tests/proxy': typeof TestsProxyRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/tests/cyclic-dependency': typeof TestsCyclicDependencyRoute
  '/tests/derived-chain': typeof TestsDerivedChainRoute
  '/tests/mounting': typeof TestsMountingRoute
  '/tests/promise': typeof TestsPromiseRoute
  '/tests/proxy': typeof TestsProxyRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/tests/cyclic-dependency': typeof TestsCyclicDependencyRoute
  '/tests/derived-chain': typeof TestsDerivedChainRoute
  '/tests/mounting': typeof TestsMountingRoute
  '/tests/promise': typeof TestsPromiseRoute
  '/tests/proxy': typeof TestsProxyRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/tests/cyclic-dependency'
    | '/tests/derived-chain'
    | '/tests/mounting'
    | '/tests/promise'
    | '/tests/proxy'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/tests/cyclic-dependency'
    | '/tests/derived-chain'
    | '/tests/mounting'
    | '/tests/promise'
    | '/tests/proxy'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/tests/cyclic-dependency'
    | '/tests/derived-chain'
    | '/tests/mounting'
    | '/tests/promise'
    | '/tests/proxy'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  TestsCyclicDependencyRoute: typeof TestsCyclicDependencyRoute
  TestsDerivedChainRoute: typeof TestsDerivedChainRoute
  TestsMountingRoute: typeof TestsMountingRoute
  TestsPromiseRoute: typeof TestsPromiseRoute
  TestsProxyRoute: typeof TestsProxyRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/proxy': {
      id: '/tests/proxy'
      path: '/tests/proxy'
      fullPath: '/tests/proxy'
      preLoaderRoute: typeof TestsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/promise': {
      id: '/tests/promise'
      path: '/tests/promise'
      fullPath: '/tests/promise'
      preLoaderRoute: typeof TestsPromiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/mounting': {
      id: '/tests/mounting'
      path: '/tests/mounting'
      fullPath: '/tests/mounting'
      preLoaderRoute: typeof TestsMountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/derived-chain': {
      id: '/tests/derived-chain'
      path: '/tests/derived-chain'
      fullPath: '/tests/derived-chain'
      preLoaderRoute: typeof TestsDerivedChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/cyclic-dependency': {
      id: '/tests/cyclic-dependency'
      path: '/tests/cyclic-dependency'
      fullPath: '/tests/cyclic-dependency'
      preLoaderRoute: typeof TestsCyclicDependencyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  TestsCyclicDependencyRoute: TestsCyclicDependencyRoute,
  TestsDerivedChainRoute: TestsDerivedChainRoute,
  TestsMountingRoute: TestsMountingRoute,
  TestsPromiseRoute: TestsPromiseRoute,
  TestsProxyRoute: TestsProxyRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
